apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql2
spec:
  selector:
    matchLabels:
      app: mysql2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql2
    spec:
      containers:
      - image: mysql:latest
        name: mysql2
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        ports:
        - containerPort: 3306
          name: mysql2
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql2
# spec:
#   ports:
#   - port: 3306
#   selector:
#     app: mysql2