apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurants-deployment
  labels:
    app: restaurant-image
spec:
  replicas: 1
  #number of replicas generated
  selector:
    #assigns labels to the pods for future selection
    matchLabels:
      app: restaurant-image
  template:
    metadata:
      labels:
        app: restaurant-image
    spec:
      containers:
      - name: restaurant-image
        image: dockersociety/leftovers1004:restaurants
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

# ---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
spec:
  type: NodePort
  selector:
    app: restaurant-image
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30100
      protocol: TCP
